// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xthxqgczkcpqsniousen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0aHhxZ2N6a2NwcXNuaW91c2VuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNTEyNjQsImV4cCI6MjA2NDkyNzI2NH0.apv64DtN0viXFLAF_glDURirR8eyMOiHRXvG-kUXmGY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);